FROM ruby:2.6.5

RUN apt-get update -qq \
    && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get install -y --no-install-recommends nodejs \
    && apt update && apt install --no-install-recommends yarn \
    && yarn global add webpack

WORKDIR /cbcapp
COPY Gemfile* /cbcapp/
COPY .ruby-version /cbcapp/
COPY package.json /cbcapp/
COPY . /cbcapp/

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]