default: &default
  adapter: postgresql
  #host: db
  #username: postgres
  #password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5
  encoding: unicode
development:
  <<: *default
  database: gwcamden_dev
test:
  <<: *default
  database: gwcamden_tst
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  encoding: unicode